### ISSUE TITLE
File "data/frames/000075.JPEG" does not exists while running greedy_tracking_from_raw_dets.py

### ISSUE THREAD

**Issue by EswarSaiKrish** [myfavouritekk/T-CNN#17]
While running this command 
` find data/vids -type f -name *.vid | python tools/tracking/greedy_tracking_from_raw_dets.py data/vids/{}.vid data/mcs_mgp/window_size_7_time_step_1_top_ratio_0.000300_top_bonus_0.400000_optflow/ data/tracks/ --thres 3.15 --max_frames 100 --num 30`

I am getting this error:
```bash
data/mcs_mgp/window_size_7_time_step_1_top_ratio_0.000300_top_bonus_0.400000_optflow/ data/tracks/ --thres 3.15 --max_frames 100 --num 30
[2018-04-04 09:04:15,303 4239 greedy_tracking_from_raw_dets.py:42 INFO] Video: {}
[2018-04-04 09:04:18,369 4239 greedy_tracking_from_raw_dets.py:58 INFO] Tracking turtle...
27
[2018-04-04 09:04:18,601 4239 track.py:219 INFO] Upon low confidence: total 0 tracks
[2018-04-04 09:04:18,602 4239 greedy_tracking_from_raw_dets.py:63 WARNING] {} has no tracks for class turtle
[2018-04-04 09:04:18,602 4239 greedy_tracking_from_raw_dets.py:58 INFO] Tracking antelope...
2
[2018-04-04 09:04:18,818 4239 track.py:219 INFO] Upon low confidence: total 0 tracks
[2018-04-04 09:04:18,820 4239 greedy_tracking_from_raw_dets.py:63 WARNING] {} has no tracks for class antelope
[2018-04-04 09:04:18,820 4239 greedy_tracking_from_raw_dets.py:58 INFO] Tracking bicycle...
4
[2018-04-04 09:04:19,042 4239 track.py:219 INFO] Upon low confidence: total 0 tracks
[2018-04-04 09:04:19,043 4239 greedy_tracking_from_raw_dets.py:63 WARNING] {} has no tracks for class bicycle
[2018-04-04 09:04:19,043 4239 greedy_tracking_from_raw_dets.py:58 INFO] Tracking lion...
16
[2018-04-04 09:04:19,265 4239 track.py:219 INFO] Upon low confidence: total 0 tracks
[2018-04-04 09:04:19,267 4239 greedy_tracking_from_raw_dets.py:63 WARNING] {} has no tracks for class lion
[2018-04-04 09:04:19,267 4239 greedy_tracking_from_raw_dets.py:58 INFO] Tracking motorcycle...
19
[2018-04-04 09:04:19,491 4239 track.py:219 INFO] Upon low confidence: total 0 tracks
[2018-04-04 09:04:19,493 4239 greedy_tracking_from_raw_dets.py:63 WARNING] {} has no tracks for class motorcycle
[2018-04-04 09:04:19,493 4239 greedy_tracking_from_raw_dets.py:58 INFO] Tracking cattle...
8
[2018-04-04 09:04:19,718 4239 track.py:219 INFO] Upon low confidence: total 0 tracks
[2018-04-04 09:04:19,719 4239 greedy_tracking_from_raw_dets.py:63 WARNING] {} has no tracks for class cattle
[2018-04-04 09:04:19,719 4239 greedy_tracking_from_raw_dets.py:58 INFO] Tracking airplane...
1
[2018-04-04 09:04:19,895 4239 track.py:222 INFO] tracking top No.0 in {}
[2018-04-04 09:04:19,896 4239 common.py:341 DEBUG] Use opened Matlab session: <matlab.engine.matlabengine.MatlabEngine object at 0x7f4b183e0690>
Error using imread (line 349)
File "data/frames/000075.JPEG" does not exist.

Error in fcn_tracker (line 11)
im1 = double(imread(im1_name));

[2018-04-04 09:04:21,946 4239 common.py:341 DEBUG] Use opened Matlab session: <matlab.engine.matlabengine.MatlabEngine object at 0x7f4b03d6f990>
Error using imread (line 349)
File "data/frames/000075.JPEG" does not exist.

Error in fcn_tracker (line 11)
im1 = double(imread(im1_name));

Traceback (most recent call last):
  File "tools/tracking/greedy_tracking_from_raw_dets.py", line 61, in <module>
    cls_idx, opts)
  File "./vdetlib/vdet/track.py", line 234, in greedily_track_from_raw_dets
    new_tracks = track_method(vid_proto, anchor_frame_id, anchor_bbox, opts)
  File "./vdetlib/vdet/track.py", line 82, in fcn_tracker
    [matlab.double(bbox),] + fw_frames + [opts.gpu,], opts.engine)
  File "./vdetlib/utils/common.py", line 345, in matlab_engine
    result = func(input_list)
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/matlabengine.py", line 84, in __call__
    _stderr).result()
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/futureresult.py", line 106, in result
    self._future,self._nargout, None, out=self._out, err=self._err)
matlab.engine.MatlabExecutionError: 
  File /usr/local/MATLAB/R2015b/toolbox/matlab/imagesci/imread.p, line 349, in imread

  File /home/eswar/T-CNN/External/fcn_tracker_matlab/fcn_tracker.m, line 11, in fcn_tracker
File "data/frames/000075.JPEG" does not exist.
```

The file 000075.JPEG is there in the data/frames directory. But I don't know why it is not looking into it.
The fcn_tracker file can be found [here](https://github.com/myfavouritekk/FCNT/blob/T-CNN/fcn_tracker.m)

**Comment by EswarSaiKrish** [comment]
The issue was solved for me. 
I opened up `$TCNN_ROOT/data/vids/{}.vid` and edited 
line 564 from 
`"root_path": "data/frames/"`
to
`"root_path": "$TCNN_ROOT/data/frames/"`
